### PR TITLE
Update class_in_python.py

### PR DESCRIPTION
**Pull request by ChiragAgg5k**
Changed class "marks" to "Marks" since camel casing is usually used for naming classes
Also reformated the file to follow PEP8

### CODE REVIEW

**Comment by ChiragAgg5k** [comment]
bsdike dikha?

**Comment by ChiragAgg5k** [comment]
bdiya

**Comment by mridulmaikhuri** [comment]
ho gaya

**Comment by mridulmaikhuri** [comment]
waise iss se hota kya hai

**Pull request merged**
